import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description:
    'Read the Privacy Policy for AHA Solutions & Systems Inc. Learn how we collect, protect, and manage your personal data in accordance with Canadian privacy laws (PIPEDA).',
};

const h2Style: React.CSSProperties = {
  fontSize: 22,
  fontWeight: 600,
  color: 'var(--text)',
  marginTop: 48,
  marginBottom: 16,
};

const h3Style: React.CSSProperties = {
  fontSize: 17,
  fontWeight: 600,
  color: 'var(--text)',
  marginTop: 32,
  marginBottom: 12,
};

const pStyle: React.CSSProperties = { marginBottom: 16 };

const ulStyle: React.CSSProperties = { paddingLeft: 20, marginBottom: 16 };

const liStyle: React.CSSProperties = { marginBottom: 8 };

export default function PrivacyPolicyPage() {
  return (
    <div className="wrap" style={{ padding: '80px 0 120px' }}>
      <h1 style={{ marginBottom: 32 }}>Privacy Policy</h1>
      <div style={{ maxWidth: 780, fontSize: 14, color: 'var(--text-2)', lineHeight: 1.7 }}>
        <p style={pStyle}>
          This Privacy Policy describes Our policies and procedures on the collection, use and
          disclosure of Your information when You use the Service and tells You about Your privacy
          rights and how the law protects You.
        </p>
        <p style={pStyle}>
          We use Your Personal data to provide and improve the Service. By using the Service, You
          agree to the collection and use of information in accordance with this Privacy Policy.
        </p>

        <h2 style={h2Style}>Interpretation &amp; Definitions</h2>

        <h3 style={h3Style}>Interpretation</h3>
        <p style={pStyle}>
          The words of which the initial letter is capitalized have meanings defined under the
          following conditions. The following definitions shall have the same meaning regardless of
          whether they appear in singular or in plural.
        </p>

        <h3 style={h3Style}>Definitions</h3>
        <p style={pStyle}>For the purposes of this Privacy Policy:</p>
        <ul style={ulStyle}>
          <li style={liStyle}>
            <strong>Account</strong> means a unique account created for You to access our Service
            or parts of our Service.
          </li>
          <li style={liStyle}>
            <strong>Partner</strong> means an entity that controls, is controlled by or is under
            common control with a party, where &ldquo;control&rdquo; means ownership of 50% or more
            equity interest or other securities entitled to vote for election of directors or other
            managing authority.
          </li>
          <li style={liStyle}>
            <strong>Company</strong> (referred to as either &ldquo;the Company&rdquo;,
            &ldquo;We&rdquo;, &ldquo;Us&rdquo; or &ldquo;Our&rdquo; in this Agreement) refers to
            AHA Solutions, Suite 502, 55 Commerce Valley Dr. W., Thornhill ON L3T7V9.
          </li>
          <li style={liStyle}>
            <strong>Cookies</strong> are small files that are placed on Your computer, mobile
            device or any other device by a website, containing the details of Your browsing history
            on that website among its many uses.
          </li>
          <li style={liStyle}>
            <strong>Country</strong> refers to: ON, CA
          </li>
          <li style={liStyle}>
            <strong>Device</strong> means any device that can access the Service such as a
            computer, a cellphone or a digital tablet.
          </li>
          <li style={liStyle}>
            <strong>Personal Data</strong> is any information that relates to an identified or
            identifiable individual.
          </li>
          <li style={liStyle}>
            <strong>Service</strong> refers to the Website.
          </li>
          <li style={liStyle}>
            <strong>Service Provider</strong> means any natural or legal person who processes the
            data on behalf of the Company. It refers to third-party companies or individuals
            employed by the Company to facilitate the Service, to provide the Service on behalf of
            the Company, to perform services related to the Service or to assist the Company in
            analyzing how the Service is used.
          </li>
          <li style={liStyle}>
            <strong>Third-party Social Media Service</strong> refers to any website or any social
            network website through which a User can log in or create an account to use the Service.
          </li>
          <li style={liStyle}>
            <strong>Usage Data</strong> refers to data collected automatically, either generated by
            the use of the Service or from the Service infrastructure itself (for example, the
            duration of a page visit).
          </li>
          <li style={liStyle}>
            <strong>Website</strong> refers to AHA Solutions accessible from{' '}
            <a href="https://www.ahasolutions.ca" style={{ color: 'var(--accent)' }}>
              https://www.ahasolutions.ca
            </a>
          </li>
          <li style={liStyle}>
            <strong>You</strong> means the individual accessing or using the Service, or the
            company, or other legal entity on behalf of which such individual is accessing or using
            the Service, as applicable.
          </li>
        </ul>

        <h2 style={h2Style}>Collecting and Using Your Personal Data</h2>

        <h3 style={h3Style}>Types of Data Collected</h3>

        <h3 style={h3Style}>Personal Data</h3>
        <p style={pStyle}>
          While using Our Service, We may ask You to provide Us with certain personally identifiable
          information that can be used to contact or identify You. Personally identifiable
          information may include, but is not limited to:
        </p>
        <ul style={ulStyle}>
          <li style={liStyle}>Email address</li>
          <li style={liStyle}>First name and last name</li>
          <li style={liStyle}>Phone number</li>
          <li style={liStyle}>Address, State, Province, ZIP/Postal code, City</li>
          <li style={liStyle}>Payment information (processed securely by third-party providers)</li>
        </ul>

        <h3 style={h3Style}>Usage Data</h3>
        <p style={pStyle}>
          Usage Data is collected automatically when using the Service. Usage Data may include
          information such as Your Device&apos;s Internet Protocol address (e.g. IP address),
          browser type, browser version, the pages of our Service that You visit, the time and date
          of Your visit, the time spent on those pages, unique device identifiers and other
          diagnostic data.
        </p>

        <h3 style={h3Style}>Information from Third-Party Social Media Services</h3>
        <p style={pStyle}>
          The Company allows You to create an account and log in to use the Service through
          Third-party Social Media Services (e.g., Google, Facebook, LinkedIn). If You decide to
          register through or otherwise grant us access to a Third-Party Social Media Service, We
          may collect Personal data that is already associated with Your Third-Party Social Media
          Service&apos;s account, such as Your name, Your email address, Your activities or Your
          contact list associated with that account.
        </p>

        <h3 style={h3Style}>Tracking Technologies and Cookies</h3>
        <p style={pStyle}>
          We use Cookies and similar tracking technologies to track the activity on Our Service and
          store certain information. Tracking technologies used are beacons, tags, and scripts to
          collect and track information and to improve and analyze Our Service.
        </p>
        <p style={pStyle}>
          We use both Session and Persistent Cookies for the purposes set out below:
        </p>
        <ul style={ulStyle}>
          <li style={liStyle}>
            <strong>Necessary / Essential Cookies (Session Cookies):</strong> Essential to provide
            You with services available through the Website and to authenticate users.
          </li>
          <li style={liStyle}>
            <strong>Functionality Cookies (Persistent Cookies):</strong> Allow us to remember
            choices You make when You use the Website, such as remembering your login details or
            language preference.
          </li>
          <li style={liStyle}>
            <strong>Tracking and Performance Cookies (Persistent Cookies):</strong> Used to track
            information about traffic to the Website and how users use the Website.
          </li>
        </ul>
        <p style={pStyle}>
          You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being
          sent.
        </p>

        <h3 style={h3Style}>Use of Your Personal Data</h3>
        <p style={pStyle}>The Company may use Personal Data for the following purposes:</p>
        <ul style={ulStyle}>
          <li style={liStyle}>To provide and maintain our Service</li>
          <li style={liStyle}>To manage Your Account</li>
          <li style={liStyle}>For the performance of a contract</li>
          <li style={liStyle}>
            To contact You by email, telephone calls, SMS, or other forms of electronic
            communication
          </li>
          <li style={liStyle}>
            To provide You with news and offers (you may unsubscribe at any time, compliant with
            CASL)
          </li>
          <li style={liStyle}>To manage Your requests</li>
          <li style={liStyle}>For business transfers</li>
        </ul>

        <h3 style={h3Style}>Retention of Your Personal Data</h3>
        <p style={pStyle}>
          The Company will retain Your Personal Data only for as long as is necessary for the
          purposes set out in this Privacy Policy.
        </p>

        <h3 style={h3Style}>Transfer of Your Personal Data</h3>
        <p style={pStyle}>
          Your information, including Personal Data, is processed at the Company&apos;s operating
          offices and in any other places where the parties involved in the processing are located.
        </p>

        <h3 style={h3Style}>Delete Your Personal Data</h3>
        <p style={pStyle}>
          You have the right to delete or request that We assist in deleting the Personal Data that
          We have collected about You.
        </p>

        <h2 style={h2Style}>Disclosure of Your Personal Data</h2>

        <h3 style={h3Style}>Business Transactions</h3>
        <p style={pStyle}>
          If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may
          be transferred.
        </p>

        <h3 style={h3Style}>Law Enforcement</h3>
        <p style={pStyle}>
          Under certain circumstances, the Company may be required to disclose Your Personal Data
          if required to do so by law or in response to valid requests by public authorities.
        </p>

        <h2 style={h2Style}>Security of Your Personal Data</h2>
        <p style={pStyle}>
          The security of Your Personal Data is important to Us. We utilize industry-standard
          security measures (such as SSL encryption) to protect your data.
        </p>

        <h2 style={h2Style}>Analytics</h2>
        <p style={pStyle}>
          We may use third-party Service providers to monitor and analyze the use of our Service:
        </p>
        <ul style={ulStyle}>
          <li style={liStyle}>Google Analytics</li>
          <li style={liStyle}>Matomo</li>
        </ul>

        <h2 style={h2Style}>Email Marketing</h2>
        <p style={pStyle}>
          We may use Your Personal Data to contact You with newsletters, marketing or promotional
          materials. You may opt-out at any time.
        </p>

        <h2 style={h2Style}>Payments</h2>
        <p style={pStyle}>
          We will not store or collect Your payment card details. That information is provided
          directly to Our third-party payment processors (PayPal, Authorize.net).
        </p>

        <h2 style={h2Style}>Behavioral Remarketing</h2>
        <p style={pStyle}>
          The Company uses remarketing services (Google Ads, Facebook) to advertise to You after
          You accessed our Service.
        </p>

        <h2 style={h2Style}>Children&apos;s Policy</h2>
        <p style={pStyle}>
          Our Service is intended for users aged 18 and older. We do not knowingly collect
          information from anyone under 18.
        </p>

        <h2 style={h2Style}>Links to Other Websites</h2>
        <p style={pStyle}>
          Our Service may contain links to other websites that are not operated by Us.
        </p>

        <h2 style={h2Style}>Changes to this Privacy Policy</h2>
        <p style={pStyle}>We may update Our Privacy Policy from time to time.</p>

        <h2 style={h2Style}>Contact Us</h2>
        <p style={pStyle}>
          If you have any questions about this Privacy Policy, You can contact us by email:{' '}
          <a href="mailto:steven@ahasolutions.ca" style={{ color: 'var(--accent)' }}>
            steven@ahasolutions.ca
          </a>
        </p>
      </div>
    </div>
  );
}
